use bankapplication;

show tables;
select * from customer_details;

desc customer_details;
desc USER_MASTER;

select * from customer_details;
ALTER TABLE customer_details auto_increment=123654;

create table USER_MASTER(
	USERID  INT(11)  primary key references CUSTOMER_DETAILS(CUST_ID),
    PASSWORD VARCHAR(20),
    ROLE VARCHAR(20),
    STATUS VARCHAR(10)
);

insert into   USER_MASTER values(6,'test','customer','active');
insert into   USER_MASTER values(3,'test','customer','active');
insert into   USER_MASTER values(7,'test','customer','active');

COMMIT;

SELECT * FROM USER_MASTER;

CREATE TABLE ACCOUNTS(
	ACCOUNT_NUMBER INT(10)  auto_increment PRIMARY KEY,
     CUST_ID  INT(11) NOT NULL,user_master
    ACCOUNT_TYPE VARCHAR(20),
    BALANCE DOUBLE(13,2),
    INTEREST_RATE DOUBLE(4,2),
   FOREIGN KEY(CUST_ID)  references CUSTOMER_DETAILS(CUST_ID)   
);

ALTER TABLE ACCOUNTS auto_increment=100001;

INSERT INTO ACCOUNTS(CUST_ID,aCCOUNT_TYPE,BALANCE,INTEREST_RATE) VALUES(6,'SAVING',5000.00,6.20);
INSERT INTO ACCOUNTS(CUST_ID,aCCOUNT_TYPE,BALANCE,INTEREST_RATE) VALUES(6,'CURRENT',25000.00,3.00);
INSERT INTO ACCOUNTS(CUST_ID,aCCOUNT_TYPE,BALANCE,INTEREST_RATE) VALUES(7,'SAVING',8500.00,7.20);
INSERT INTO ACCOUNTS(CUST_ID,aCCOUNT_TYPE,BALANCE,INTEREST_RATE) VALUES(3,'SAVING',2500.00,4.20);


Select * from customer_details;
SELECT * FROM ACCOUNTS where cust_Id= 3 ;

SELECT * FROM ACCOUNTS ;

select c.customer_name, a.account_number, a.Account_type, a.balance from customer_details as c join ACCOUNTS as a on c.cust_id = a.cust_id where c.cust_id=7;

COMMIT;

select * from Accounts;

CREATE TABLE BENEFICIARY_DETAILS(
	BENE_ID INT(10) auto_increment PRIMARY KEY,
    IFSC_CODE VARCHAR(10) ,
    BENE_NAME VARCHAR(20) NOT NULL,
    BENE_ACCOUNT_NUMBER INT(10) NOT NULL,
    CUST_ID INT(11) NOT NULL,
    foreign key(CUST_ID) references ACCOUNTS(CUST_ID)    
);

Alter table BENEFICIARY_DETAILS Add column Account_Type varchar(15) ;

update   BENEFICIARY_DETAILS set IFSC_code='ABC123' where CUST_id=7;

ALTER TABLE BENEFICIARY_DETAILS  auto_increment=1111;

ALTER TABLE BENEFICIARY_DETAILS add constraint custid_accno_bene unique key(`BENE_ACCOUNT_NUMBER`,`CUST_ID`);

INSERT INTO BENEFICIARY_DETAILS(IFSC_CODE,BENE_NAME,BENE_ACCOUNT_NUMBER,CUST_ID) VALUES(NULL,'ANIL',100003,6);
INSERT INTO BENEFICIARY_DETAILS(IFSC_CODE,BENE_NAME,BENE_ACCOUNT_NUMBER,CUST_ID) VALUES(NULL,'ANIL',100003,7);
INSERT INTO BENEFICIARY_DETAILS(IFSC_CODE,BENE_NAME,BENE_ACCOUNT_NUMBER,CUST_ID) VALUES(NULL,'ANIL_6',100001,3);
INSERT INTO BENEFICIARY_DETAILS(IFSC_CODE,BENE_NAME,BENE_ACCOUNT_NUMBER,CUST_ID) VALUES(NULL,'ANIL_15',100002,3);

SELECT * FROM BENEFICIARY_DETAILS;

desc BENEFICIARY_DETAILS;

CREATE TABLE TRANSACTIONS(
	TRANSACTION_ID INT(15)  auto_increment primary KEY,
    CUSTOMER_ACC_NO INT(10) NOT NULL,
    TRANSACTION_AMOUNT DOUBLE(13,2) NOT NULL,
    TRANSACTION_TYPE VARCHAR(15) NOT NULL,
    TRANSACTION_DETAILS VARCHAR(50) ,
    CUSTOMER_BALANCE DOUBLE(13,2),
    TRANSACTION_TIME_STAMP datetime,
    BENE_ACC_ID INT(10) NOT NULL      
);


ALTER TABLE TRANSACTIONS auto_increment=111111;
COMMIT;

INSERT INTO TRANSACTIONS(CUSTOMER_ACC_NO,TRANSACTION_AMOUNT,TRANSACTION_TYPE,TRANSACTION_DETAILS,CUSTOMER_BALANCE,TRANSACTION_TIME_STAMP,BENE_ACC_ID)
	VALUES(100001,1000.00,'WITHDRAW','PAYMENT TO BENE',4000.00,now(),1111);
    
INSERT INTO TRANSACTIONS(CUSTOMER_ACC_NO,TRANSACTION_AMOUNT,TRANSACTION_TYPE,TRANSACTION_DETAILS,CUSTOMER_BALANCE,TRANSACTION_TIME_STAMP,BENE_ACC_ID)
	VALUES(100003,1000.00,'DEPOSIT','PAYMENT TO BENE',3500.00,now(),100001);

UPDATE  ACCOUNTS SET BALANCE = 4000.00 WHERE ACCOUNT_NUMBER=100001;

UPDATE  ACCOUNTS SET BALANCE = 3500.00 WHERE ACCOUNT_NUMBER=100003;

INSERT INTO TRANSACTIONS(CUSTOMER_ACC_NO,TRANSACTION_AMOUNT,TRANSACTION_TYPE,TRANSACTION_DETAILS,CUSTOMER_BALANCE,TRANSACTION_TIME_STAMP,BENE_ACC_ID)
	VALUES(100003,500.00,'WITHDRAW','PAYMENT FOR CHARGES TO CLIENT',3000.00,now(),100001);
    
INSERT INTO TRANSACTIONS(CUSTOMER_ACC_NO,TRANSACTION_AMOUNT,TRANSACTION_TYPE,TRANSACTION_DETAILS,CUSTOMER_BALANCE,TRANSACTION_TIME_STAMP,BENE_ACC_ID)
	VALUES(100001,500.00,'DEPOSIT','PAYMENT FOR CHARGES TO CLIENT',4500.00,now(),100003);
    
UPDATE  ACCOUNTS SET BALANCE = 3000.00 WHERE ACCOUNT_NUMBER=100003;

UPDATE  ACCOUNTS SET BALANCE = 4500.00 WHERE ACCOUNT_NUMBER=100001;


#---------------

INSERT INTO TRANSACTIONS(CUSTOMER_ACC_NO,TRANSACTION_AMOUNT,TRANSACTION_TYPE,TRANSACTION_DETAILS,CUSTOMER_BALANCE,TRANSACTION_TIME_STAMP,BENE_ACC_ID)
	VALUES(100003,200.00,'WITHDRAW','PAYMENT FOR FEES CONS',2800.00,now(),100002);
    
INSERT INTO TRANSACTIONS(CUSTOMER_ACC_NO,TRANSACTION_AMOUNT,TRANSACTION_TYPE,TRANSACTION_DETAILS,CUSTOMER_BALANCE,TRANSACTION_TIME_STAMP,BENE_ACC_ID)
	VALUES(100002,200.00,'DEPOSIT','PAYMENT FOR FEES CONS',8700.00,now(),100003);
    
UPDATE  ACCOUNTS SET BALANCE = 2800.00 WHERE ACCOUNT_NUMBER=100003;

UPDATE  ACCOUNTS SET BALANCE = 8700.00 WHERE ACCOUNT_NUMBER=100002;

COMMIT;

SELECT * FROM TRANSACTIONS;

SELECT * FROM TRANSACTIONS WHERE CUSTOMER_aCC_NO= (select ACCOUNT_NUMBER FROM ACCOUNTS WHERE CUST_ID=3);

select * from customer_table;
select * from customer_account;

select * from customer_details;
select * from ACCOUNTS;

select * from beneficiary_details;
desc beneficiary_details;

desc customer_details;

delete from  TRANSACTIONS where transaction_id=111130;
desc USER_MASTER;